# Generated by Django 5.0.6 on 2024-07-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine2_machine3_rename_machine_machine1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine1',
            new_name='Machine',
        ),
        migrations.DeleteModel(
            name='Machine2',
        ),
        migrations.DeleteModel(
            name='Machine3',
        ),
    ]
