# Generated by Django 5.0.7 on 2024-08-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_rename_machine1_machine_delete_machine2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('found_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
