# Generated by Django 5.0.7 on 2024-08-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_logistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsBox',
            fields=[
                ('logistics_box_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Logistics',
        ),
        migrations.AddField(
            model_name='exception',
            name='logistics_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='machines.logisticsbox'),
        ),
    ]
