# Generated by Django 5.0.7 on 2024-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_exception_logisticsbox_delete_logistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logisticsbox',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
