# Generated by Django 5.0.7 on 2024-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_exception_flag_logisticsbox_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_box_id', models.IntegerField()),
                ('logistics_box_timestamp', models.DateTimeField()),
                ('number_units', models.IntegerField()),
                ('article_number', models.CharField(max_length=255)),
                ('product_box_id', models.IntegerField()),
                ('product_serial', models.CharField(max_length=255)),
                ('device_creation_timestamp', models.DateTimeField()),
                ('device_remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
