# Generated by Django 5.0.6 on 2024-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_productbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbox',
            name='product_serial',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
